(Endeavour setup): install Rust from the website instead of system package

diff --git a/endeavour-setup b/endeavour-setup
--- a/endeavour-setup
+++ b/endeavour-setup
@@ -204,7 +204,6 @@ pkg+=( redis )
 pkg+=( remmina )
 pkg+=( ripgrep )
 pkg+=( rpi-imager )
-pkg+=( rustup )
 pkg+=( seahorse )
 pkg+=( smplayer )
 pkg+=( strawberry )
@@ -269,6 +268,13 @@ pkg+=( org.kde.kmines )
 pkg+=( org.nickvision.tubeconverter )
 
 sudo flatpak install -y flathub ${pkg[*]} || fail "Flatpak installation error"
+
+step-header "Rust"
+
+if ! which rustup >> /dev/null; then
+    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > /tmp/rustup-installer.sh || fail "Rustup download error"
+    sh /tmp/rustup-installer.sh -y --no-modify-path || "Rust installation error"
+fi
 
 step-header "Bluetooth"
 
