(Endeavour setup): move Flatpak installation

diff --git a/endeavour-setup b/endeavour-setup
--- a/endeavour-setup
+++ b/endeavour-setup
@@ -211,7 +211,7 @@ pkg+=( ukui-wallpapers )
 
 sudo pacman -S --needed --noconfirm ${pkg[*]} || fail "Theming packages error"
 
-step-header "AUR"
+step-header "AUR packages"
 
 aur=""
 # aur="${aur} anki"
@@ -223,6 +223,20 @@ aur="${aur} php-amqp"
 if [[ "$aur" != '' ]]; then
     yay -S --needed --noconfirm $aur || fail 'AUR installation error'
 fi
+
+step-header "Flatpak packages"
+
+pkg=( com.getpostman.Postman )
+pkg+=( com.spotify.Client )
+pkg+=( com.visualstudio.code )
+pkg+=( cc.arduino.IDE2 )
+pkg+=( io.github.ungoogled_software.ungoogled_chromium )
+pkg+=( net.ankiweb.Anki )
+pkg+=( net.cozic.joplin_desktop )
+pkg+=( org.freefilesync.FreeFileSync )
+pkg+=( org.nickvision.tubeconverter )
+
+sudo flatpak install -y flathub ${pkg[*]} || fail "Flatpak installation error"
 
 step-header "Node"
 
@@ -327,20 +341,6 @@ sudo groupadd -f dialout &&
 step-header "Rust"
 
 rustup default stable
-
-step-header "Flatpak packages"
-
-pkg=( com.getpostman.Postman )
-pkg+=( com.spotify.Client )
-pkg+=( com.visualstudio.code )
-pkg+=( cc.arduino.IDE2 )
-pkg+=( io.github.ungoogled_software.ungoogled_chromium )
-pkg+=( net.ankiweb.Anki )
-pkg+=( net.cozic.joplin_desktop )
-pkg+=( org.freefilesync.FreeFileSync )
-pkg+=( org.nickvision.tubeconverter )
-
-sudo flatpak install -y flathub ${pkg[*]} || fail "Flatpak installation error"
 
 # step-header "SSH agent finder"
 #
