(Fedora setup): add Grub timeout change

diff --git a/fedora-setup b/fedora-setup
--- a/fedora-setup
+++ b/fedora-setup
@@ -205,6 +205,13 @@ if [ ! -d ~/Documents/tmux-themepack ]; then
         fail 'Tmux themepack error'
 fi
 
+step-header 'Grub'
+if ! grep -q 'GRUB_TIMEOUT=1' /etc/default/grub; then
+    sudo sed -i 's/GRUB_TIMEOUT=./GRUB_TIMEOUT=1/' /etc/default/grub &&
+    grub2-mkconfig -o /boot/grub2/grub.cfg ||
+    fail 'Grub error'
+fi
+
 step-header 'NPM global packages'
 if ! which tldr; then
     sudo npm install -g tldr &&
