manually add changed from conflicted commits
The changes are:

- (Manjaro setup, Fedora setup): symlinks cleanup, copy new symlinks from Manjaro to Fedora
- (Manjaro setup): add linking of a couple more dotfiles
- (Manjaro setup): fix wrong nextcloud package, fix yay options, add Plover
- (Fedora setup): cleanup

diff --git a/fedora-setup b/fedora-setup
--- a/fedora-setup
+++ b/fedora-setup
@@ -1,6 +1,10 @@
 #!/usr/bin/env bash
 # shellcheck disable=SC2015
 
+#############
+# Functions #
+#############
+
 step-header() {
   echo -e '\n\e[93m\e[1m------------------------------'
   echo "$1"
@@ -12,6 +16,10 @@ fail() {
     exit 1
 }
 
+########
+# Init #
+########
+
 osVer=$(rpm -E %fedora)
 
 if [ "$USER" = root ]; then
@@ -21,6 +29,7 @@ if [ "$USER" = root ]; then
 fi
 
 step-header "SSH" 
+
 if [ ! -f ~/.ssh/id_ed25519.pub ]; then
     # shellcheck disable=SC2034
     ssh-keygen -t ed25519 &&
@@ -33,7 +42,12 @@ if [ ! -f ~/.ssh/config ]; then
     echo 'AddKeysToAgent yes' > ~/.ssh/config
 fi
 
-step-header "Packages (early)"
+########################
+# Installation (early) #
+########################
+
+step-header "Packages"
+
 sudo dnf install -y \
     git \
     gtk2 \
@@ -41,73 +55,19 @@ sudo dnf install -y \
     nextcloud-client ||
     fail "Early packages installation error"
 
-step-header "Snapd and Snap packages (you'll probably have to restart the script once because of a \"too early for operation\" error)"
-sudo dnf install -y \
-    snapd &&
-    sudo snap install redis-desktop-manager &&
-    sudo snap install postman &&
-    sudo snap install spotify ||
-    fail "Snap installation error"
-
-#step-header "Vivaldi"
-#if ! which vivaldi; then
-#    echo "Go to https://vivaldi.com/pl/download/"
-#    read -rp "Press Enter after installation is finished"
-#fi
-
-#step-header "Skype"
-#if ! which skypeforlinux; then
-#    echo "Go to https://www.skype.com/pl/get-skype/"
-#    read -rp "Press Enter after installation is finished"
-#fi
-
-step-header "Docker"
-if ! which docker; then
-    sudo dnf -y install dnf-plugins-core &&
-        sudo dnf config-manager -y --add-repo https://download.docker.com/linux/fedora/docker-ce.repo &&
-        sudo dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin ||
-        fail 'Docker installation error'
-    sudo systemctl enable docker ||
-        fail 'Docker service enabling error'
-fi
-
-if ! systemctl is-active -q docker; then
-    sudo systemctl start docker ||
-        fail 'Docker service start error'
-fi
-
-sudo usermod -aG docker "$USER" ||
-    fail 'Docker usermod error'
-
-step-header "Jetbrains Toolbox"
-if [ ! -d ~/.local/share/JetBrains/Toolbox ]; then
-    echo "Go to https://www.jetbrains.com/toolbox-app/"
-    read -rp "Press Enter after installation is finished"
-fi
-
-# Installed manually because dark theme was glitchy when installed as a snap.
-step-header "DBeaver"
-if ! which dbeaver; then
-    echo "Go to https://dbeaver.io/download/"
-    read -rp "Press Enter after installation is finished"
-fi
-
-# step-header "VS Code"
-# if ! which code; then
-#     sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc &&
-#     sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo' &&
-#     sudo dnf check-update; 
-#     sudo dnf install code -y ||
-#     fail "VS Code installation error"
-# fi
-
 step-header "FreeFileSync"
+
 if ! which freefilesync; then
     echo "Go to https://freefilesync.org/download.php"
     read -rp "Press Enter after installation is finished"
 fi
 
+################
+# Installation #
+################
+
 step-header 'RPM Fusion'
+
 baseUrl='https://download1.rpmfusion.org/free/'
 if ! dnf repolist | grep -q 'RPM Fusion'; then
     sudo dnf install \
@@ -119,6 +79,7 @@ else
 fi
 
 step-header "DNF packages"
+
 sudo dnf install -y \
     audacity \
     baobab \
@@ -158,21 +119,116 @@ sudo dnf install -y \
     zsh ||
     fail "DNF installation error"
 
-step-header "Bin folder"
-if [ ! -d ~/bin ]; then
-    cd ~ &&
-        git clone git@github.com:rafalglowacz/bin.git ||
-        fail "Bin error"
+# step-header "Jetbrains Toolbox"
+# if [ ! -d ~/.local/share/JetBrains/Toolbox ]; then
+#     echo "Go to https://www.jetbrains.com/toolbox-app/"
+#     read -rp "Press Enter after installation is finished"
+# fi
+
+# Installed manually because dark theme was glitchy when installed as a snap.
+step-header "DBeaver"
+
+if ! which dbeaver; then
+    echo "Go to https://dbeaver.io/download/"
+    read -rp "Press Enter after installation is finished"
+fi
+
+step-header "Docker"
+
+if ! which docker; then
+    sudo dnf -y install dnf-plugins-core &&
+        sudo dnf config-manager -y --add-repo https://download.docker.com/linux/fedora/docker-ce.repo &&
+        sudo dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin ||
+        fail 'Docker installation error'
+    sudo systemctl enable docker ||
+        fail 'Docker service enabling error'
+fi
+
+if ! systemctl is-active -q docker; then
+    sudo systemctl start docker ||
+        fail 'Docker service start error'
+fi
+
+sudo usermod -aG docker "$USER" ||
+    fail 'Docker usermod error'
+
+step-header 'FZF'
+
+if [ ! -d ~/.fzf ]; then
+    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf &&
+        ~/.fzf/install --key-bindings --completion --update-rc ||
+        fail 'FZF error'
+fi
+
+step-header 'Git Trim'
+
+if ! which git-trim; then
+    sudo npm install -g git-trim ||
+    fail "Git Trim installation error"
+fi
+
+step-header 'Plover'
+
+sudo groupadd -f dialout &&
+    sudo usermod -aG dialout $USER ||
+    fail "Failed to add user to dialout group"
+
+step-header 'QMK'
+
+if ! which qmk; then
+    python3 -m pip install --user qmk ||
+        fail "QMK installation error"
 fi
 
 step-header "SSH agent finder"
+
 if [ ! -d ~/bin/ssh-find-agent ]; then
     cd ~/bin &&
     git clone https://github.com/wwalker/ssh-find-agent.git ||
     fail "SSH finder error"
 fi
 
+step-header "Snapd and Snap packages (you'll probably have to restart the script once because of a \"too early for operation\" error)"
+
+sudo dnf install -y \
+    snapd &&
+    sudo snap install redis-desktop-manager &&
+    sudo snap install postman &&
+    sudo snap install spotify ||
+    fail "Snap installation error"
+
+step-header "Teensy loader (for keyboard firmware)"
+
+if ! which teensy_loader_cli; then
+    cd /tmp &&
+    rm -rf teensy_loader_cli &&
+    git clone https://github.com/PaulStoffregen/teensy_loader_cli.git &&
+    cd teensy_loader_cli &&
+    make &&
+    sudo mv teensy_loader_cli /usr/local/bin ||
+    fail "Teensy loader installation error"
+fi
+
+step-header 'TLDR'
+
+if ! which tldr; then
+    sudo npm install -g tldr &&
+    tldr -u ||
+    fail "TLDR installation error"
+fi
+
+###############################
+# Configuration, themes, etc. #
+###############################
+
+step-header 'DNF config'
+
+if ! grep -q 'defaultyes' /etc/dnf/dnf.conf; then
+    sudo sh -c 'echo defaultyes=True >> /etc/dnf/dnf.conf'
+fi
+
 step-header 'Dotfiles'
+
 [ ! -d ~/Dev ] && mkdir ~/Dev
 
 if [ ! -d ~/Dev/dotfiles ]; then
@@ -181,7 +237,53 @@ if [ ! -d ~/Dev/dotfiles ]; then
         fail 'Dotfiles error'
 fi
 
-step-header 'ZSH add-ons'
+step-header 'Grub'
+
+if ! grep -q 'GRUB_TIMEOUT=1' /etc/default/grub; then
+    sudo sed -i 's/GRUB_TIMEOUT=./GRUB_TIMEOUT=1/' /etc/default/grub &&
+    sudo grub2-mkconfig -o /boot/grub2/grub.cfg ||
+    fail 'Grub error'
+fi
+
+step-header 'Symlinks'
+
+[ ! -d ~/.config/kitty ] && mkdir ~/.config/kitty
+
+rm -f ~/.gitconfig &&
+    ln -sf ~/Dev/dotfiles/gitconfig ~/.gitconfig &&
+    ln -sf ~/Dev/dotfiles/kitty.conf ~/.config/kitty/kitty.conf &&
+    ln -sf ~/Dev/dotfiles/kitty-startup ~/.config/kitty/startup &&
+    ln -sf ~/Dev/dotfiles/tmux.conf ~/.tmux.conf &&
+    ln -sf ~/Dev/dotfiles/manjaro-omz.zshrc ~/.zshrc &&
+    ln -sf ~/Dev/dotfiles/vcs-exclusions ~/.vcs-exclusions &&
+    ln -sf ~/Dev/dotfiles/zsh/candy.zsh-theme ~/.oh-my-zsh/custom/themes/candy.zsh-theme ||
+    fail 'Symlinks error'
+
+step-header 'Tmux themes'
+
+if [ ! -d ~/Documents/tmux-themepack ]; then
+    cd ~/Documents &&
+        git clone https://github.com/jimeh/tmux-themepack.git ||
+        fail 'Tmux themepack error'
+fi
+
+step-header "Basic NVim"
+
+if [ ! -d ~/.config/nvim ]; then
+    ln -s ~/Dev/dotfiles/vim/basic ~/.config/nvim
+fi
+
+step-header "NVim"
+
+if [ ! -d ~/.config/nvim-astro ]; then
+    mkdir ~/.config/nvim-astro
+    cd ~/.config/nvim-astro
+    git clone --depth 1 https://github.com/AstroNvim/AstroNvim nvim
+    ln -s ~/Dev/dotfiles/vim/astro ~/.config/nvim-astro/nvim/lua/user
+fi
+
+step-header 'ZSH'
+
 if [ ! -d ~/.oh-my-zsh ]; then
     sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended ||
     fail 'OMZ error'
@@ -198,95 +300,6 @@ fi
 if [ ! -d ~/.oh-my-zsh/custom/plugins/command-time ]; then
     git clone https://github.com/popstas/zsh-command-time.git ~/.oh-my-zsh/custom/plugins/command-time ||
         fail 'ZSH command time error'
-fi
-
-step-header 'Symlinks'
-[ ! -d ~/.config/kitty ] && mkdir ~/.config/kitty
-
-rm -f ~/.gitconfig &&
-    rm -f ~/.config/kitty/kitty.conf &&
-    rm -f ~/.config/kitty/startup &&
-    rm -f ~/.tmux.conf &&
-    rm -f ~/.zshrc &&
-    ln -s ~/Dev/dotfiles/gitconfig ~/.gitconfig &&
-    ln -s ~/Dev/dotfiles/kitty.conf ~/.config/kitty/kitty.conf &&
-    ln -s ~/Dev/dotfiles/kitty-startup ~/.config/kitty/startup &&
-    ln -s ~/Dev/dotfiles/tmux.conf ~/.tmux.conf &&
-    ln -s ~/Dev/dotfiles/manjaro-omz.zshrc ~/.zshrc ||
-    fail 'Symlinks error'
-
-step-header 'FZF'
-if [ ! -d ~/.fzf ]; then
-    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf &&
-        ~/.fzf/install --key-bindings --completion --update-rc ||
-        fail 'FZF error'
-fi
-
-step-header 'Tmux themes'
-if [ ! -d ~/Documents/tmux-themepack ]; then
-    cd ~/Documents &&
-        git clone https://github.com/jimeh/tmux-themepack.git ||
-        fail 'Tmux themepack error'
-fi
-
-step-header 'Grub'
-if ! grep -q 'GRUB_TIMEOUT=1' /etc/default/grub; then
-    sudo sed -i 's/GRUB_TIMEOUT=./GRUB_TIMEOUT=1/' /etc/default/grub &&
-    sudo grub2-mkconfig -o /boot/grub2/grub.cfg ||
-    fail 'Grub error'
-fi
-
-step-header 'DNF config'
-if ! grep -q 'defaultyes' /etc/dnf/dnf.conf; then
-    sudo sh -c 'echo defaultyes=True >> /etc/dnf/dnf.conf'
-fi
-
-step-header 'TLDR'
-if ! which tldr; then
-    sudo npm install -g tldr &&
-    tldr -u ||
-    fail "TLDR installation error"
-fi
-
-step-header 'QMK'
-if ! which qmk; then
-    python3 -m pip install --user qmk ||
-        fail "QMK installation error"
-fi
-
-step-header 'Plover'
-sudo groupadd -f dialout &&
-    sudo usermod -aG dialout $USER ||
-    fail "Failed to add user to dialout group"
-
-step-header 'Git Trim'
-if ! which git-trim; then
-    sudo npm install -g git-trim ||
-    fail "Git Trim installation error"
-fi
-
-step-header "Basic NVim"
-if [ ! -d ~/.config/nvim ]; then
-    ln -s ~/Dev/dotfiles/vim/basic ~/.config/nvim
-fi
-
-step-header "NVim"
-if [ ! -d ~/.config/nvim-astro ]; then
-    mkdir ~/.config/nvim-astro
-    cd ~/.config/nvim-astro
-    git clone --depth 1 https://github.com/AstroNvim/AstroNvim nvim
-    ln -s ~/Dev/dotfiles/vim/astro ~/.config/nvim-astro/nvim/lua/user
-fi
-
-step-header "Teensy loader (for keyboard firmware)"
-if ! which teensy_loader_cli; then
-    cd /tmp &&
-    rm -rf teensy_loader_cli &&
-    git clone https://github.com/PaulStoffregen/teensy_loader_cli.git &&
-    cd teensy_loader_cli &&
-    make &&
-    sudo mv teensy_loader_cli /usr/local/bin ||
-    fail "Teensy loader installation error"
 fi
 
 echo -e '\n\e[32m\e[1m------------------------------'
diff --git a/manjaro-setup b/manjaro-setup
--- a/manjaro-setup
+++ b/manjaro-setup
@@ -38,14 +38,14 @@ sudo timedatectl set-local-rtc 1 ||
 step-header "Pamac packages (early)"
 sudo pamac install --no-confirm \
     keepassxc \
-    nextcloud \
+    nextcloud-client \
     yay ||
     fail "Pamac installation (early) error"
 
 step-header "FreeFileSync"
 
 if [ ! -f /opt/freefilesync/FreeFileSync ]; then
-    yay -S --answerdiff None --answerclean None --removemake \
+    yay -S --noconfirm \
         freefilesync-bin ||
         fail 'FreeFileSync installation error'
 fi
@@ -107,15 +107,20 @@ sudo pamac install --no-confirm \
 step-header 'Yay packages'
 
 # if ! which jetbrains-toolbox; then
-#     yay -S --answerdiff None --answerclean None --removemake \
+#     yay -S --noconfirm \
 #         jetbrains-toolbox ||
 #         fail 'JetBrains Toolbox installation error'
 # fi
 
 if ! which postman; then
-    yay -S --answerdiff None --answerclean None --removemake \
+    yay -S --noconfirm \
         postman-bin ||
         fail 'Postman installation error'
+fi
+
+if ! which plover; then
+    yay -S --noconfirm plover ||
+        fail 'Plover installation error'
 fi
 
 step-header "Snapd and Snap packages (you'll probably have to restart the script once because of a \"too early for operation\" error)"
@@ -187,15 +192,13 @@ step-header 'Symlinks'
 [ ! -d ~/.config/kitty ] && mkdir ~/.config/kitty
 
 rm -f ~/.gitconfig &&
-    rm -f ~/.config/kitty/kitty.conf &&
-    rm -f ~/.config/kitty/startup &&
-    rm -f ~/.tmux.conf &&
-    rm -f ~/.zshrc &&
-    ln -s ~/Dev/dotfiles/gitconfig ~/.gitconfig &&
-    ln -s ~/Dev/dotfiles/kitty.conf ~/.config/kitty/kitty.conf &&
-    ln -s ~/Dev/dotfiles/kitty-startup ~/.config/kitty/startup &&
-    ln -s ~/Dev/dotfiles/tmux.conf ~/.tmux.conf &&
-    ln -s ~/Dev/dotfiles/manjaro-omz.zshrc ~/.zshrc ||
+    ln -sf ~/Dev/dotfiles/gitconfig ~/.gitconfig &&
+    ln -sf ~/Dev/dotfiles/kitty.conf ~/.config/kitty/kitty.conf &&
+    ln -sf ~/Dev/dotfiles/kitty-startup ~/.config/kitty/startup &&
+    ln -sf ~/Dev/dotfiles/tmux.conf ~/.tmux.conf &&
+    ln -sf ~/Dev/dotfiles/manjaro-omz.zshrc ~/.zshrc &&
+    ln -sf ~/Dev/dotfiles/vcs-exclusions ~/.vcs-exclusions &&
+    ln -sf ~/Dev/dotfiles/zsh/candy.zsh-theme ~/.oh-my-zsh/custom/themes/candy.zsh-theme ||
     fail 'Symlinks error'
 
 step-header 'FZF'
