show step headers, add Docker Compose

diff --git a/ubuntu-setup b/ubuntu-setup
--- a/ubuntu-setup
+++ b/ubuntu-setup
@@ -1,12 +1,18 @@
 #!/usr/bin/env bash
 
+step-header() {
+  echo -e '\e[93m\e[1m------------------------------'
+  echo "$1"
+  echo -e '------------------------------\e[0m\n'
+}
+
 if [ "$USER" = root ]; then
     # We need $USER to be our regular user, not root, so this script shouldn't be run with sudo.
     echo "Please run this script without sudo and as a regular user. Sudo will be added where necessary."
     exit 1
 fi
 
-# SSH key
+step-header 'SSH'
 if [ ! -f ~/.ssh/id_ed25519.pub ]; then
     # shellcheck disable=SC2034
     ssh-keygen -t ed25519 &&
@@ -15,34 +21,42 @@ if [ ! -f ~/.ssh/id_ed25519.pub ]; then
         (echo 'SSH error' && exit 1)
 fi
 
-# Global settings
-timedatectl set-local-rtc 1 || (echo 'Settings error' && exit 1)
+step-header 'Global settings'
+timedatectl set-local-rtc 1 ||
+    (echo 'Settings error' && exit 1)
 
-# Package installation
+step-header 'Packages'
 sudo apt install -y meld git vim gnome-tweaks dconf-editor xdotool php-cli keepassxc zsh tmux docker.io curl &&
     sudo snap install spotify &&
     sudo snap install skype &&
     sudo usermod -aG docker "$USER" ||
     (echo 'Installation error' && exit 1)
 
-# Bin folder
+step-header 'Docker compose'
+if ! which docker-compose; then
+    sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+    sudo chmod +x /usr/local/bin/docker-compose ||
+    (echo 'Docker Compose error' && exit 1)
+fi
+
+step-header 'Bin folder'
 if [ ! -d ~/bin ]; then
     cd ~ &&
         git clone git@github.com:rafalglowacz/bin.git ||
         (echo 'Bin error' && exit 1)
 fi
 
-# SSH agent finder
+step-header 'SSH agent finder'
 if [ ! -d ~/bin/ssh-find-agent ]; then
     cd ~/bin &&
     git clone git@github.com:wwalker/ssh-find-agent.git ||
     (echo 'SSH finder error' && exit 1)
 fi
 
-# Key bindings
+step-header 'Key bindings'
 ~/bin/keybinds-set 2>&1 | grep -v 'No such schema'
 
-# Dotfiles
+step-header 'Dotfiles'
 [ ! -d ~/Dev ] && mkdir ~/Dev
 
 if [ ! -d ~/Dev/dotfiles ]; then
@@ -51,7 +65,7 @@ if [ ! -d ~/Dev/dotfiles ]; then
         (echo 'Dotfiles error' && exit 1)
 fi
 
-# ZSH add-ons
+step-header 'ZSH add-ons'
 if [ ! -d ~/.oh-my-zsh ]; then
     sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" ||
     (echo 'OMZ error' && exit 1)
@@ -62,7 +76,7 @@ if [ ! -d ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions ]; then
     echo 'ZSH autosuggestions error' && exit 1
 fi
 
-# Symlinks
+step-header 'Symlinks'
 rm ~/.zshrc &&
     rm ~/.tmux.conf &&
     rm ~/.ackrc &&
@@ -73,21 +87,20 @@ rm ~/.zshrc &&
     ln -s ~/Dev/dotfiles/gitconfig ~/.gitconfig ||
     (echo 'Symlinks error' && exit 1)
 
-# FZF
+step-header 'FZF'
 if [ ! -d ~/.fzf ]; then
     git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf &&
         ~/.fzf/install ||
         (echo 'FZF error' && exit 1)
 fi
 
-# Tmux themes
+step-header 'Tmux themes'
 if [ ! -d ~/Documents/tmux-themepack ]; then
     cd ~/Documents &&
         git clone git@github.com:jimeh/tmux-themepack.git ||
         (echo 'Tmux themepack error' && exit 1)
 fi
 
-#
-echo -e '\n\e[32m\e[1m-----'
+echo -e '\n\e[32m\e[1m------------------------------'
 echo 'Done'
-echo -e '-----\e[0m'
+echo -e '------------------------------\e[0m'
