add Tmux theme pack, add parentheses that are apparently needed

diff --git a/ubuntu-setup b/ubuntu-setup
--- a/ubuntu-setup
+++ b/ubuntu-setup
@@ -9,23 +9,23 @@ if [ ! -f ~/.ssh/id_ed25519.pub ]; then
     # shellcheck disable=SC2034
     ssh-keygen -t ed25519 &&
         cat ~/.ssh/id_ed25519.pub &&
-        read -rp "Press Enter after saving the SSH key to Github" confirm || echo 'SSH error' && exit 1
+        read -rp "Press Enter after saving the SSH key to Github" confirm || (echo 'SSH error' && exit 1)
 fi
 
 timedatectl set-local-rtc 1 &&
     sudo apt install -y meld git vim gnome-tweaks dconf-editor xdotool php-cli keepassxc zsh tmux docker.io curl &&
     sudo snap install spotify &&
     sudo snap install skype &&
-    sudo usermod -aG docker "$USER" || echo 'Installation error' && exit 1
+    sudo usermod -aG docker "$USER" || (echo 'Installation error' && exit 1)
 
 if [ ! -d ~/bin ]; then
     cd ~ &&
-        git clone git@github.com:rafalglowacz/bin.git || echo 'Bin error' && exit 1
+        git clone git@github.com:rafalglowacz/bin.git || (echo 'Bin error' && exit 1)
 fi
 
 if [ ! -d ~/bin/ssh-find-agent ]; then
     cd ~/bin &&
-    git clone git@github.com:wwalker/ssh-find-agent.git || echo 'SSH finder error' && exit 1
+    git clone git@github.com:wwalker/ssh-find-agent.git || (echo 'SSH finder error' && exit 1)
 fi
 
 ~/bin/keybinds-set
@@ -34,15 +34,16 @@ fi
 
 if [ ! -d ~/Dev/dotfiles ]; then
     cd ~/Dev &&
-        git clone git@github.com:rafalglowacz/dotfiles.git || echo 'Dotfiles error' && exit 1
+        git clone git@github.com:rafalglowacz/dotfiles.git || (echo 'Dotfiles error' && exit 1)
 fi
 
 if [ ! -d ~/.oh-my-zsh ]; then
-    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || echo 'OMZ error' && exit 1
+    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || (echo 'OMZ error' && exit 1)
 fi
 
 if [ ! -d ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions ]; then
-    git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
+    git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions ||
+    echo 'ZSH autosuggestions error' && exit 1
 fi
 
 rm ~/.zshrc &&
@@ -52,11 +53,16 @@ rm ~/.zshrc &&
     ln -s ~/Dev/dotfiles/manjaro-omz.zshrc ~/.zshrc &&
     ln -s ~/Dev/dotfiles/tmux.conf ~/.tmux.conf &&
     ln -s ~/Dev/dotfiles/ackrc.ackrc ~/.ackrc &&
-    ln -s ~/Dev/dotfiles/gitconfig ~/.gitconfig || echo 'Symlinks error' && exit 1
+    ln -s ~/Dev/dotfiles/gitconfig ~/.gitconfig || (echo 'Symlinks error' && exit 1)
 
 if [ ! -d ~/.fzf ]; then
     git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf &&
-        ~/.fzf/install || echo 'FZF error' && exit 1
+        ~/.fzf/install || (echo 'FZF error' && exit 1)
+fi
+
+if [ ! -d ~/Documents/tmux-themepack ]; then
+    cd ~/Documents &&
+        git clone git@github.com:jimeh/tmux-themepack.git || (echo 'Tmux themepack error' && exit 1)
 fi
 
 echo 'Done!'
