replace instances of echo && exit with a call to fail() in Ubuntu setup script

diff --git a/ubuntu-setup b/ubuntu-setup
--- a/ubuntu-setup
+++ b/ubuntu-setup
@@ -6,6 +6,11 @@ step-header() {
   echo -e '------------------------------\e[0m\n'
 }
 
+fail() {
+    echo "$1"
+    exit 1
+}
+
 if [ "$USER" = root ]; then
     # We need $USER to be our regular user, not root, so this script shouldn't be run with sudo.
     echo "Please run this script without sudo and as a regular user. Sudo will be added where necessary."
@@ -18,7 +23,7 @@ if [ ! -f ~/.ssh/id_ed25519.pub ]; then
     ssh-keygen -t ed25519 &&
         cat ~/.ssh/id_ed25519.pub &&
         read -rp "Press Enter after saving the SSH key to Github" confirm ||
-        (echo 'SSH error' && exit 1)
+        fail 'SSH error'
 fi
 
 if [ ! -f ~/.ssh/config ]; then
@@ -27,7 +32,7 @@ fi
 
 step-header 'Global settings'
 timedatectl set-local-rtc 1 ||
-    (echo 'Settings error' && exit 1)
+    fail 'Settings error'
 
 step-header 'Packages'
 sudo apt install -y \
@@ -68,27 +73,27 @@ sudo apt install -y \
     sudo snap install slack --classic &&
     sudo snap install spotify &&
     sudo usermod -aG docker "$USER" ||
-    (echo 'Installation error' && exit 1)
+    fail 'Installation error'
 
 step-header 'Docker compose'
 if ! which docker-compose; then
     sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
     sudo chmod +x /usr/local/bin/docker-compose ||
-    (echo 'Docker Compose error' && exit 1)
+    fail 'Docker Compose error'
 fi
 
 step-header 'Bin folder'
 if [ ! -d ~/bin ]; then
     cd ~ &&
         git clone git@github.com:rafalglowacz/bin.git ||
-        (echo 'Bin error' && exit 1)
+        fail 'Bin error'
 fi
 
 step-header 'SSH agent finder'
 if [ ! -d ~/bin/ssh-find-agent ]; then
     cd ~/bin &&
     git clone git@github.com:wwalker/ssh-find-agent.git ||
-    (echo 'SSH finder error' && exit 1)
+    fail 'SSH finder error'
 fi
 
 step-header 'Key bindings'
@@ -100,21 +105,21 @@ step-header 'Dotfiles'
 if [ ! -d ~/Dev/dotfiles ]; then
     cd ~/Dev &&
         git clone git@github.com:rafalglowacz/dotfiles.git ||
-        (echo 'Dotfiles error' && exit 1)
+        fail 'Dotfiles error'
 fi
 
 step-header 'ZSH add-ons'
 if [ ! -d ~/.oh-my-zsh ]; then
     sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended ||
-    (echo 'OMZ error' && exit 1)
+    fail 'OMZ error'
 fi
 
 sudo chsh -s "$(which zsh)" "$USER" ||
-    (echo 'Default shell change error' && exit 1)
+    fail 'Default shell change error'
 
 if [ ! -d ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions ]; then
     git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions ||
-    (echo 'ZSH autosuggestions error' && exit 1)
+    fail 'ZSH autosuggestions error'
 fi
 
 step-header 'Symlinks'
@@ -126,27 +131,27 @@ rm ~/.zshrc &&
     ln -s ~/Dev/dotfiles/tmux.conf ~/.tmux.conf &&
     ln -s ~/Dev/dotfiles/ackrc.ackrc ~/.ackrc &&
     ln -s ~/Dev/dotfiles/gitconfig ~/.gitconfig ||
-    (echo 'Symlinks error' && exit 1)
+    fail 'Symlinks error'
 
 step-header 'FZF'
 if [ ! -d ~/.fzf ]; then
     git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf &&
         ~/.fzf/install --key-bindings --completion --update-rc &&
-        (echo 'FZF error' && exit 1)
+        fail 'FZF error'
 fi
 
 step-header 'Tmux themes'
 if [ ! -d ~/Documents/tmux-themepack ]; then
     cd ~/Documents &&
         git clone git@github.com:jimeh/tmux-themepack.git ||
-        (echo 'Tmux themepack error' && exit 1)
+        fail 'Tmux themepack error'
 fi
 
 step-header 'Grub'
 if [[ $(grep 'GRUB_TIMEOUT=0' /etc/default/grub) ]]; then
     sudo sed -i 's/GRUB_TIMEOUT=0/GRUB_TIMEOUT=1/' /etc/default/grub &&
     sudo update-grub ||
-    (echo 'Grub error' && exit 1)
+    fail 'Grub error'
 fi
 
 step-header 'NPM global packages'
