bring Ubuntu setup script up-to-date with more recently used setup scripts

diff --git a/ubuntu-setup b/ubuntu-setup
--- a/ubuntu-setup
+++ b/ubuntu-setup
@@ -38,10 +38,10 @@ timedatectl set-local-rtc 1 ||
 step-header 'Packages'
 sudo apt install -y \
     ack-grep \
+    baobab \
     bat \
     composer \
     curl \
-    dconf-editor \
     default-jdk \
     default-jre \
     docker.io \
@@ -49,32 +49,44 @@ sudo apt install -y \
     fonts-powerline \
     gimp \
     git \
-    gnome-tweaks \
     gparted \
+    gnome-keyring \
     htop \
     iotop \
     jq \
     keepassxc \
+    kitty \
     libreoffice \
     lynx \
     meld \
     net-tools \
+    nextcloud-desktop \
     nodejs \
     npm \
     php-cli \
+    php-gd \
     powerline \
-    ripgrep \
+    remmina \
+    thunderbird \
     tmux \
     tree \
     vim \
     xclip \
     xdotool \
     zsh &&
-    sudo snap install skype &&
-    sudo snap install slack --classic &&
-    sudo snap install spotify &&
     sudo usermod -aG docker "$USER" ||
     fail 'Installation error'
+
+step-header 'Snap packages'
+sudo snap install code --classic &&
+    sudo snap install dbeaver-ce &&
+    sudo snap install skype &&
+    sudo snap install redis-desktop-manager ||
+    fail 'Snap installation error'
+
+step-header "Flatpak packages"
+sudo flatpak install -y com.getpostman.Postman ||
+  fail "Flatpak installation error"
 
 step-header 'Docker compose'
 if ! which docker-compose; then
@@ -82,6 +94,13 @@ if ! which docker-compose; then
     sudo chmod +x /usr/local/bin/docker-compose ||
     fail 'Docker Compose error'
 fi
+
+step-header 'PHP'
+phpDir=$(ls -1d /etc/php/* | tail -n 1) &&
+    sudo sed -i 's/;extension=exif/extension=exif/' "$phpDir/cli/php.ini" &&
+    sudo sed -i 's/;extension=gd/extension=gd/' "$phpDir/cli/php.ini" &&
+    sudo sed -i 's/;extension=soap/extension=soap/' "$phpDir/cli/php.ini" ||
+    fail 'PHP extension enabling error'
 
 step-header 'Bin folder'
 if [ ! -d ~/bin ]; then
@@ -96,9 +115,6 @@ if [ ! -d ~/bin/ssh-find-agent ]; then
     git clone git@github.com:wwalker/ssh-find-agent.git ||
     fail 'SSH finder error'
 fi
-
-step-header 'Key bindings'
-~/bin/keybinds-set-gnome 2>&1 | grep -v 'No such schema'
 
 step-header 'Dotfiles'
 [ ! -d ~/Dev ] && mkdir ~/Dev
@@ -124,14 +140,19 @@ if [ ! -d ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions ]; then
 fi
 
 step-header 'Symlinks'
-rm -f ~/.zshrc &&
-    rm -f ~/.tmux.conf &&
-    rm -f ~/.ackrc &&
+[ ! -d ~/.config/kitty ] && mkdir ~/.config/kitty
+rm -f ~/.ackrc &&
     rm -f ~/.gitconfig &&
-    ln -s ~/Dev/dotfiles/manjaro-omz.zshrc ~/.zshrc &&
-    ln -s ~/Dev/dotfiles/tmux.conf ~/.tmux.conf &&
+    rm -f ~/.config/kitty/kitty.conf &&
+    rm -f ~/.config/kitty/startup &&
+    rm -f ~/.tmux.conf &&
+    rm -f ~/.zshrc &&
     ln -s ~/Dev/dotfiles/ackrc.ackrc ~/.ackrc &&
-    ln -s ~/Dev/dotfiles/gitconfig ~/.gitconfig ||
+    ln -s ~/Dev/dotfiles/gitconfig ~/.gitconfig &&
+    ln -s ~/Dev/dotfiles/kitty.conf ~/.config/kitty/kitty.conf &&
+    ln -s ~/Dev/dotfiles/kitty-startup ~/.config/kitty/startup &&
+    ln -s ~/Dev/dotfiles/manjaro-omz.zshrc ~/.zshrc &&
+    ln -s ~/Dev/dotfiles/tmux.conf ~/.tmux.conf ||
     fail 'Symlinks error'
 
 step-header 'FZF'
@@ -149,8 +170,8 @@ if [ ! -d ~/Documents/tmux-themepack ]; then
 fi
 
 step-header 'Grub'
-if [[ $(grep 'GRUB_TIMEOUT=0' /etc/default/grub) ]]; then
-    sudo sed -i 's/GRUB_TIMEOUT=0/GRUB_TIMEOUT=1/' /etc/default/grub &&
+if ! grep -q 'GRUB_TIMEOUT=1' /etc/default/grub; then
+    sudo sed -i 's/GRUB_TIMEOUT=./GRUB_TIMEOUT=1/' /etc/default/grub &&
     sudo update-grub ||
     fail 'Grub error'
 fi
@@ -158,6 +179,10 @@ fi
 step-header 'NPM global packages'
 if ! which tldr; then
     sudo npm install -g tldr
+fi
+
+if ! which git-trim; then
+    sudo npm install -g git-trim
 fi
 
 echo -e '\n\e[32m\e[1m------------------------------'
