add comments, add green color to final success output

diff --git a/ubuntu-setup b/ubuntu-setup
--- a/ubuntu-setup
+++ b/ubuntu-setup
@@ -6,6 +6,7 @@ if [ "$USER" = root ]; then
     exit 1
 fi
 
+# SSH key
 if [ ! -f ~/.ssh/id_ed25519.pub ]; then
     # shellcheck disable=SC2034
     ssh-keygen -t ed25519 &&
@@ -14,27 +15,34 @@ if [ ! -f ~/.ssh/id_ed25519.pub ]; then
         (echo 'SSH error' && exit 1)
 fi
 
-timedatectl set-local-rtc 1 &&
-    sudo apt install -y meld git vim gnome-tweaks dconf-editor xdotool php-cli keepassxc zsh tmux docker.io curl &&
+# Global settings
+timedatectl set-local-rtc 1 || (echo 'Settings error' && exit 1)
+
+# Package installation
+sudo apt install -y meld git vim gnome-tweaks dconf-editor xdotool php-cli keepassxc zsh tmux docker.io curl &&
     sudo snap install spotify &&
     sudo snap install skype &&
     sudo usermod -aG docker "$USER" ||
     (echo 'Installation error' && exit 1)
 
+# Bin folder
 if [ ! -d ~/bin ]; then
     cd ~ &&
         git clone git@github.com:rafalglowacz/bin.git ||
         (echo 'Bin error' && exit 1)
 fi
 
+# SSH agent finder
 if [ ! -d ~/bin/ssh-find-agent ]; then
     cd ~/bin &&
     git clone git@github.com:wwalker/ssh-find-agent.git ||
     (echo 'SSH finder error' && exit 1)
 fi
 
+# Key bindings
 ~/bin/keybinds-set 2>&1 | grep -v 'No such schema'
 
+# Dotfiles
 [ ! -d ~/Dev ] && mkdir ~/Dev
 
 if [ ! -d ~/Dev/dotfiles ]; then
@@ -43,6 +51,7 @@ if [ ! -d ~/Dev/dotfiles ]; then
         (echo 'Dotfiles error' && exit 1)
 fi
 
+# ZSH add-ons
 if [ ! -d ~/.oh-my-zsh ]; then
     sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" ||
     (echo 'OMZ error' && exit 1)
@@ -53,6 +62,7 @@ if [ ! -d ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions ]; then
     echo 'ZSH autosuggestions error' && exit 1
 fi
 
+# Symlinks
 rm ~/.zshrc &&
     rm ~/.tmux.conf &&
     rm ~/.ackrc &&
@@ -63,16 +73,21 @@ rm ~/.zshrc &&
     ln -s ~/Dev/dotfiles/gitconfig ~/.gitconfig ||
     (echo 'Symlinks error' && exit 1)
 
+# FZF
 if [ ! -d ~/.fzf ]; then
     git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf &&
         ~/.fzf/install ||
         (echo 'FZF error' && exit 1)
 fi
 
+# Tmux themes
 if [ ! -d ~/Documents/tmux-themepack ]; then
     cd ~/Documents &&
         git clone git@github.com:jimeh/tmux-themepack.git ||
         (echo 'Tmux themepack error' && exit 1)
 fi
 
-echo 'Done!'
+#
+echo -e '\n\e[32m\e[1m-----'
+echo 'Done'
+echo -e '-----\e[0m'
